const DURATION__FIVE_SECONDS    = 5_000
const DURATION__TEN_SECONDS     = 10_000
const DURATION__THIRTY_SECONDS  = 30_000
const DURATION__SIXTY_SECONDS   = 60_000

export {
  DURATION__FIVE_SECONDS,
  DURATION__TEN_SECONDS,
  DURATION__THIRTY_SECONDS,
  DURATION__SIXTY_SECONDS,
}
