// Consts
import { DURATION__TEN_SECONDS, DURATION__THIRTY_SECONDS, DURATION__SIXTY_SECONDS } from '@jsconsts/consts'

const DEFAULT_GNOSIS_ICON_URL = 'https://gnosisscan.io/images/svg/brands/main.svg'

const DEFAULT_GNOSIS_EXPLORER_BASE_URI = 'https://gnosis.blockscout.com'
const DEFAULT_ETHEREUM_EXPLORER_BASE_URI = 'https://eth.blockscout.com/'

const EXPLORER_DEFAULT_TX_URI = '/tx/'
const DEFAULT_GNOSIS_EXPLORER_TX_URI = EXPLORER_DEFAULT_TX_URI
const DEFAULT_ETHEREUM_EXPLORER_TX_URI = EXPLORER_DEFAULT_TX_URI

// Toasts durations
const TOAST_DURATION_SHORT = DURATION__TEN_SECONDS
const TOAST_DURATION_MEDIUM = DURATION__THIRTY_SECONDS
const TOAST_DURATION_LONG = DURATION__SIXTY_SECONDS
// Toasts positions
const TOAST_BOTTOM_RIGHT_POSITION = 'bottom-right'
const TOAST_DEFAULT_POSITION = TOAST_BOTTOM_RIGHT_POSITION

// Errors
// Metamask: MetaMask Tx Signature: User denied transaction signature.
// Rabby: TransactionExecutionError User rejected the request.
const USER_REJECT_TX_REGEXP = /user\s+(rejected|denied)/i

// Timeout for tx
const DURATION_TX_TIMEOUT = DURATION__SIXTY_SECONDS * 2

// Give up data fetching after 5 retries
const FETCHDATA_MULTICALL_MAX_RETRY = 5
// Multicall success status
const FETCHDATA_MULTICALL_SUCCESSSTATUS = 'success'
// Wait for n seconds after transfer before balance refresh
const REFRESH_BALANCE_DELAY_AFTER_TRANSFER = DURATION__TEN_SECONDS

export {
	TOAST_DURATION_SHORT,
	TOAST_DURATION_MEDIUM,
	TOAST_DURATION_LONG,
	TOAST_DEFAULT_POSITION,
	DEFAULT_GNOSIS_ICON_URL,
	DEFAULT_GNOSIS_EXPLORER_BASE_URI,
	DEFAULT_ETHEREUM_EXPLORER_BASE_URI,
	DEFAULT_GNOSIS_EXPLORER_TX_URI,
	DEFAULT_ETHEREUM_EXPLORER_TX_URI,
	USER_REJECT_TX_REGEXP,
	DURATION_TX_TIMEOUT,
	FETCHDATA_MULTICALL_MAX_RETRY,
	FETCHDATA_MULTICALL_SUCCESSSTATUS,
	REFRESH_BALANCE_DELAY_AFTER_TRANSFER,
}
